#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-maps

maps:
  google:
    api_key: AIzaSyCQqGskh4ilLlX-HeAiui5TbHd6EMr4GzI
    marker_cluster:
        enabled: true

paginate: 9
paginate_path: "/points-de-vente/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /points-de-vente/:slug
  - scope:
      path: '_products'
    values:
      permalink: /produits/:slug
  - scope:
      path: '_tasteit'
    values:
      permalink: /point-de-degustation/:slug

collections:
  products:
    output: true
  tasteit:
    output: true

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed